language: ruby
rvm: 2.2
sudo: required
cache:
  directories:
  - "$HOME/.berkshelf"
addons:
  apt:
    sources:
    - chef-stable-precise
    packages:
    - chefdk
env:
  matrix:
  - CHEF_BIN=/opt/chefdk/bin
  global:
  - secure: NZWqG4aOtcpAlzTW8IwlGXpuFydRooSDQYAgYh9ZOZq9v0o0F3Kkkl1YXAX4vTgw1n7HP0FzAXxE/5BWPxTmC3VrnYsij4q1t/CK5qXyUhGmdbczi5b19SAF1+ydY+ijROqYJQenFTRECWexV/E1GQJoBpsodqDw59tAwZ6/6+s=
  - secure: dXLiwjvBCw/ShnTjK2nKvxTFFLOUYKcoa+yIxYaSaYlsgrQSoxRNFmFoKT+oFFdGPy62YCxO4fTLYdpggMT2NWPN+yY1z7TtA0cmEtJg2gjyh8s0QzUnCDQ3MHNxmr/cSmr9ErSZtpUCTXWF8iLK8rvbz5dF3dF/vfANlxjfbB8=
before_install:
- openssl aes-256-cbc -K $encrypted_387c33f5486d_key -iv $encrypted_387c33f5486d_iv
  -in travis_ci_ec2.pem.enc -out ~/.ssh/travis_ci_ec2.pem -d
- mkdir ~/.chef
- echo 'node_name "trubot"' >> ~/.chef/knife.rb
- chmod 600 ~/.ssh/travis_ci_ec2.pem
install:
- eval "$(${CHEF_BIN}/chef shell-init bash)"
- "${CHEF_BIN}/berks"
before_script:
- "${CHEF_BIN}/chef --version"
- "${CHEF_BIN}/rubocop --version"
- "${CHEF_BIN}/foodcritic --version"
script:
- "${CHEF_BIN}/rubocop"
- "${CHEF_BIN}/foodcritic ."
- "${CHEF_BIN}/kitchen test -c"
notifications:
  slack:
    secure: BAQINrDya9sAN0OBHkzwNaQj7NlJ8ebxIHbZGhtXgMfX2LAv9VcSMoJ99pssyXARuhwo3BRkTscAhTyrvekZci3WakeaolVhXvHVMdPp+JPKcle580K1kcwt5OVghHCc5nAc9s1aoCgFEyRSYVgQynaNjDWdEDRUbQe4xE028OI=
