language: ruby
cache: bundler
rvm:
- 2.1
bundler_args: "--without integration --retry 3"
before_script:
- bundle exec berks
script:
- bundle exec rake travis
notifications:
  slack:
    secure: "BAQINrDya9sAN0OBHkzwNaQj7NlJ8ebxIHbZGhtXgMfX2LAv9VcSMoJ99pssyXARuhwo3BRkTscAhTyrvekZci3WakeaolVhXvHVMdPp+JPKcle580K1kcwt5OVghHCc5nAc9s1aoCgFEyRSYVgQynaNjDWdEDRUbQe4xE028OI="
